// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package models

import (
	"database/sql"
	"time"

	"github.com/tabbed/pqtype"
)

type TrackerBodyPart struct {
	Name         string    `json:"name"`
	Region       string    `json:"region"`
	UpperOrLower string    `json:"upperOrLower"`
	CretTs       time.Time `json:"cretTs"`
	UpdtTs       time.Time `json:"updtTs"`
}

type TrackerComposition struct {
	SubmittedOn  string         `json:"submittedOn"`
	Weight       string         `json:"weight"`
	Bodyfat      string         `json:"bodyfat"`
	Neck         sql.NullString `json:"neck"`
	Shoulders    sql.NullString `json:"shoulders"`
	LeftBicep    sql.NullString `json:"leftBicep"`
	RightBicep   sql.NullString `json:"rightBicep"`
	LeftTricep   sql.NullString `json:"leftTricep"`
	RightTricep  sql.NullString `json:"rightTricep"`
	LeftForearm  sql.NullString `json:"leftForearm"`
	RightForearm sql.NullString `json:"rightForearm"`
	Chest        sql.NullString `json:"chest"`
	Waist        sql.NullString `json:"waist"`
	LeftQuad     sql.NullString `json:"leftQuad"`
	RightQuad    sql.NullString `json:"rightQuad"`
	LeftCalf     sql.NullString `json:"leftCalf"`
	RightCalf    sql.NullString `json:"rightCalf"`
	CretTs       time.Time      `json:"cretTs"`
	UpdtTs       time.Time      `json:"updtTs"`
}

type TrackerExercise struct {
	Name      string         `json:"name"`
	Type      sql.NullString `json:"type"`
	Variation sql.NullString `json:"variation"`
	CretTs    time.Time      `json:"cretTs"`
	UpdtTs    time.Time      `json:"updtTs"`
}

type TrackerExerciseDetail struct {
	ExerciseName string    `json:"exerciseName"`
	BodyPart     string    `json:"bodyPart"`
	Level        string    `json:"level"`
	CretTs       time.Time `json:"cretTs"`
	UpdtTs       time.Time `json:"updtTs"`
}

type TrackerExercisePerformed struct {
	ID            int32          `json:"id"`
	SetID         int32          `json:"setID"`
	ExerciseName  string         `json:"exerciseName"`
	Reps          int16          `json:"reps"`
	Weight        int16          `json:"weight"`
	RepsInReserve sql.NullString `json:"repsInReserve"`
	CretTs        time.Time      `json:"cretTs"`
	UpdtTs        time.Time      `json:"updtTs"`
}

type TrackerNutrition struct {
	SubmittedOn    string                `json:"submittedOn"`
	Calories       int16                 `json:"calories"`
	Protein        sql.NullInt16         `json:"protein"`
	Carbohydrate   sql.NullInt16         `json:"carbohydrate"`
	Fat            sql.NullInt16         `json:"fat"`
	Micronutrients pqtype.NullRawMessage `json:"micronutrients"`
	CretTs         time.Time             `json:"cretTs"`
	UpdtTs         time.Time             `json:"updtTs"`
}

type TrackerProgram struct {
	Name   string    `json:"name"`
	CretTs time.Time `json:"cretTs"`
	UpdtTs time.Time `json:"updtTs"`
}

type TrackerProgramDetail struct {
	ProgramName string    `json:"programName"`
	WorkoutName string    `json:"workoutName"`
	CretTs      time.Time `json:"cretTs"`
	UpdtTs      time.Time `json:"updtTs"`
}

type TrackerSetPerformed struct {
	ID        int32     `json:"id"`
	SetNumber int16     `json:"setNumber"`
	WorkoutID int32     `json:"workoutID"`
	GroupID   int16     `json:"groupID"`
	CretTs    time.Time `json:"cretTs"`
	UpdtTs    time.Time `json:"updtTs"`
}

type TrackerWorkout struct {
	Name        string    `json:"name"`
	ProgramName string    `json:"programName"`
	CretTs      time.Time `json:"cretTs"`
	UpdtTs      time.Time `json:"updtTs"`
}

type TrackerWorkoutDetail struct {
	WorkoutName  string        `json:"workoutName"`
	GroupID      int16         `json:"groupID"`
	ExerciseName string        `json:"exerciseName"`
	Sets         int16         `json:"sets"`
	Reps         int16         `json:"reps"`
	Weight       sql.NullInt16 `json:"weight"`
	CretTs       time.Time     `json:"cretTs"`
	UpdtTs       time.Time     `json:"updtTs"`
}

type TrackerWorkoutPerformed struct {
	ID          int32     `json:"id"`
	SubmittedOn time.Time `json:"submittedOn"`
	WorkoutName string    `json:"workoutName"`
	CretTs      time.Time `json:"cretTs"`
	UpdtTs      time.Time `json:"updtTs"`
}
